### ISSUE TITLE
Implement Highlight/Fill Cell feature

### ISSUE THREAD

**Issue by parjanya-rajput** [MSTC-DA-IICT/Hacktoberfest2023-SudoDroids#1]
On touch, highlight that cell by different colour and highlight the corresponding rows and columns

**Comment by prakharbhatnagar20** [comment]
Hey! Can you please assign me this issue

**Comment by parjanya-rajput** [comment]
How do you plan to implement it?

**Comment by prakharbhatnagar20** [comment]
I will create 3 functions in BoardSudoku.kt
1) An override method onTouchEvent which will respond to a touch.
2) A function that will take canvas which will iterate over the corresponding rows and columns.
3) A helper method which will take a canvas, row, column and paint and will use drawRect to draw the rectangle from start of the cell to the start of another cell.

**Comment by parjanya-rajput** [comment]
Ok your approach seems correct go ahead!!

**Comment by parjanya-rajput** [comment]
Try the tough one too:)
