### ISSUE TITLE
Design and Implement Splash Screen

### ISSUE THREAD

**Issue by parjanya-rajput** [MSTC-DA-IICT/Hacktoberfest2023-SudoDroids#4]
Summary:
We need to design and implement a splash screen for our app to provide users with a visually appealing and branded loading experience.

Scope:
The scope of this issue includes:

Designing a captivating and on-brand splash screen image or animation.
Implementing the splash screen logic to display it when the app is launched.
Configuring the splash screen's duration to ensure a smooth transition to the main app interface.

**Comment by deepanshubarve** [comment]
hey parjanya ,
i have some this type of splash screen , could you please assign me this issue

**Comment by parjanya-rajput** [comment]
Can you share the design like it should be related to the app in some way..

**Comment by deepanshubarve** [comment]
it could be like in gamified way ,like a small sudoku playing animation appear with the name of app . It should be match with the blue theme of app according to login page

**Comment by parjanya-rajput** [comment]
Go ahead with it

**Comment by parjanya-rajput** [comment]
Go ahead

**Comment by parjanya-rajput** [comment]
Try the tough one

**Comment by parjanya-rajput** [comment]
Go ahead implement lottie animations splash screen
